# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  before_all do
    setup_circle_ci
  end

  lane :beta do
    current_date = Time.now.strftime("%Y%m%d%H%M%S")
    increment_build_number(build_number: current_date)
    build_app(scheme: "Tight")
    app_store_connect_api_key(
      key_id: "QQT3769X94",
      issuer_id: "69a6de85-1535-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./AuthKey_QQT3769X94.p8",
      is_key_content_base64: false,
      duration: 1200, # optional (maximum 1200)
      in_house: false # optional but may be required if using match/sigh
    )
    upload_to_testflight
  end

  desc "Run all the tests"
  lane :test do
    scan(
      scheme: "Tight",
      clean: true,

      # issue: xcrun simctl spawn 
      # see here: https://github.com/fastlane/fastlane/issues/17753
      include_simulator_logs: false
    )
  end
end
